/*
 * Auto-generated libhybris wrapper for libbinder_ndk.so.
 * See generator.py.
 *
 * The autogenerated file is considered to have the same copyright as the
 * input files.
 *
 * Copyright (C) 2018, The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <dlfcn.h>

extern "C" {
    #include <hybris/common/binding.h>
}

#ifndef __clang__
#   define _Nullable
#   define _Nonnull
#endif

HYBRIS_LIBRARY_INITIALIZE(libbinder_ndk, "libbinder_ndk.so")


#include <android/binder_parcel.h>

HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, void, AParcel_delete, AParcel*)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, binder_status_t, AParcel_setDataPosition, const AParcel*, int32_t)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, int32_t, AParcel_getDataPosition, const AParcel*)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, binder_status_t, AParcel_writeStrongBinder, AParcel*, AIBinder*)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, binder_status_t, AParcel_readStrongBinder, const AParcel*, AIBinder**)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, binder_status_t, AParcel_writeParcelFileDescriptor, AParcel*, int)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, binder_status_t, AParcel_readParcelFileDescriptor, const AParcel*, int*)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, binder_status_t, AParcel_writeStatusHeader, AParcel*, const AStatus*)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, binder_status_t, AParcel_readStatusHeader, const AParcel*, AStatus**)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, binder_status_t, AParcel_writeString, AParcel*, const char*, int32_t)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, binder_status_t, AParcel_readString, const AParcel*, void*, AParcel_stringAllocator)
HYBRIS_IMPLEMENT_FUNCTION4(libbinder_ndk, binder_status_t, AParcel_writeStringArray, AParcel*, const void*, int32_t, AParcel_stringArrayElementGetter)
HYBRIS_IMPLEMENT_FUNCTION4(libbinder_ndk, binder_status_t, AParcel_readStringArray, const AParcel*, void*, AParcel_stringArrayAllocator, AParcel_stringArrayElementAllocator)
HYBRIS_IMPLEMENT_FUNCTION4(libbinder_ndk, binder_status_t, AParcel_writeParcelableArray, AParcel*, const void*, int32_t, AParcel_writeParcelableElement)
HYBRIS_IMPLEMENT_FUNCTION4(libbinder_ndk, binder_status_t, AParcel_readParcelableArray, const AParcel*, void*, AParcel_parcelableArrayAllocator, AParcel_readParcelableElement)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, binder_status_t, AParcel_writeInt32, AParcel*, int32_t)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, binder_status_t, AParcel_writeUint32, AParcel*, uint32_t)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, binder_status_t, AParcel_writeInt64, AParcel*, int64_t)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, binder_status_t, AParcel_writeUint64, AParcel*, uint64_t)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, binder_status_t, AParcel_writeFloat, AParcel*, float)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, binder_status_t, AParcel_writeDouble, AParcel*, double)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, binder_status_t, AParcel_writeBool, AParcel*, bool)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, binder_status_t, AParcel_writeChar, AParcel*, char16_t)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, binder_status_t, AParcel_writeByte, AParcel*, int8_t)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, binder_status_t, AParcel_readInt32, const AParcel*, int32_t*)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, binder_status_t, AParcel_readUint32, const AParcel*, uint32_t*)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, binder_status_t, AParcel_readInt64, const AParcel*, int64_t*)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, binder_status_t, AParcel_readUint64, const AParcel*, uint64_t*)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, binder_status_t, AParcel_readFloat, const AParcel*, float*)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, binder_status_t, AParcel_readDouble, const AParcel*, double*)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, binder_status_t, AParcel_readBool, const AParcel*, bool*)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, binder_status_t, AParcel_readChar, const AParcel*, char16_t*)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, binder_status_t, AParcel_readByte, const AParcel*, int8_t*)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, binder_status_t, AParcel_writeInt32Array, AParcel*, const int32_t*, int32_t)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, binder_status_t, AParcel_writeUint32Array, AParcel*, const uint32_t*, int32_t)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, binder_status_t, AParcel_writeInt64Array, AParcel*, const int64_t*, int32_t)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, binder_status_t, AParcel_writeUint64Array, AParcel*, const uint64_t*, int32_t)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, binder_status_t, AParcel_writeFloatArray, AParcel*, const float*, int32_t)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, binder_status_t, AParcel_writeDoubleArray, AParcel*, const double*, int32_t)
HYBRIS_IMPLEMENT_FUNCTION4(libbinder_ndk, binder_status_t, AParcel_writeBoolArray, AParcel*, const void*, int32_t, AParcel_boolArrayGetter)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, binder_status_t, AParcel_writeCharArray, AParcel*, const char16_t*, int32_t)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, binder_status_t, AParcel_writeByteArray, AParcel*, const int8_t*, int32_t)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, binder_status_t, AParcel_readInt32Array, const AParcel*, void*, AParcel_int32ArrayAllocator)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, binder_status_t, AParcel_readUint32Array, const AParcel*, void*, AParcel_uint32ArrayAllocator)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, binder_status_t, AParcel_readInt64Array, const AParcel*, void*, AParcel_int64ArrayAllocator)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, binder_status_t, AParcel_readUint64Array, const AParcel*, void*, AParcel_uint64ArrayAllocator)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, binder_status_t, AParcel_readFloatArray, const AParcel*, void*, AParcel_floatArrayAllocator)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, binder_status_t, AParcel_readDoubleArray, const AParcel*, void*, AParcel_doubleArrayAllocator)
HYBRIS_IMPLEMENT_FUNCTION4(libbinder_ndk, binder_status_t, AParcel_readBoolArray, const AParcel*, void*, AParcel_boolArrayAllocator, AParcel_boolArraySetter)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, binder_status_t, AParcel_readCharArray, const AParcel*, void*, AParcel_charArrayAllocator)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, binder_status_t, AParcel_readByteArray, const AParcel*, void*, AParcel_byteArrayAllocator)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, binder_status_t, AParcel_reset, AParcel*)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, int32_t, AParcel_getDataSize, const AParcel*)
HYBRIS_IMPLEMENT_FUNCTION4(libbinder_ndk, binder_status_t, AParcel_appendFrom, const AParcel*, AParcel*, int32_t, int32_t)
HYBRIS_IMPLEMENT_FUNCTION0(libbinder_ndk, AParcel*, AParcel_create)
HYBRIS_IMPLEMENT_FUNCTION4(libbinder_ndk, binder_status_t, AParcel_marshal, const AParcel*, uint8_t*, size_t, size_t)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, binder_status_t, AParcel_unmarshal, AParcel*, const uint8_t*, size_t)

#include <android/binder_status.h>

HYBRIS_IMPLEMENT_FUNCTION0(libbinder_ndk, AStatus*, AStatus_newOk)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, AStatus*, AStatus_fromExceptionCode, binder_exception_t)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, AStatus*, AStatus_fromExceptionCodeWithMessage, binder_exception_t, const char*)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, AStatus*, AStatus_fromServiceSpecificError, int32_t)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, AStatus*, AStatus_fromServiceSpecificErrorWithMessage, int32_t, const char*)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, AStatus*, AStatus_fromStatus, binder_status_t)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, bool, AStatus_isOk, const AStatus*)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, binder_exception_t, AStatus_getExceptionCode, const AStatus*)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, int32_t, AStatus_getServiceSpecificError, const AStatus*)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, binder_status_t, AStatus_getStatus, const AStatus*)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, const char*, AStatus_getMessage, const AStatus*)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, const char*, AStatus_getDescription, const AStatus*)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, void, AStatus_deleteDescription, const char*)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, void, AStatus_delete, AStatus*)

#include <android/persistable_bundle.h>

HYBRIS_IMPLEMENT_FUNCTION0(libbinder_ndk, APersistableBundle*, APersistableBundle_new)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, APersistableBundle*, APersistableBundle_dup, const APersistableBundle*)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, void, APersistableBundle_delete, APersistableBundle*)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, bool, APersistableBundle_isEqual, const APersistableBundle*, const APersistableBundle*)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, binder_status_t, APersistableBundle_readFromParcel, const AParcel*, APersistableBundle**)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, binder_status_t, APersistableBundle_writeToParcel, const APersistableBundle*, AParcel*)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, int32_t, APersistableBundle_size, const APersistableBundle*)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, int32_t, APersistableBundle_erase, APersistableBundle*, const char*)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, void, APersistableBundle_putBoolean, APersistableBundle*, const char*, bool)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, void, APersistableBundle_putInt, APersistableBundle*, const char*, int32_t)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, void, APersistableBundle_putLong, APersistableBundle*, const char*, int64_t)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, void, APersistableBundle_putDouble, APersistableBundle*, const char*, double)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, void, APersistableBundle_putString, APersistableBundle*, const char*, const char*)
HYBRIS_IMPLEMENT_FUNCTION4(libbinder_ndk, void, APersistableBundle_putBooleanVector, APersistableBundle*, const char*, const bool*, int32_t)
HYBRIS_IMPLEMENT_FUNCTION4(libbinder_ndk, void, APersistableBundle_putIntVector, APersistableBundle*, const char*, const int32_t*, int32_t)
HYBRIS_IMPLEMENT_FUNCTION4(libbinder_ndk, void, APersistableBundle_putLongVector, APersistableBundle*, const char*, const int64_t*, int32_t)
HYBRIS_IMPLEMENT_FUNCTION4(libbinder_ndk, void, APersistableBundle_putDoubleVector, APersistableBundle*, const char*, const double*, int32_t)
HYBRIS_IMPLEMENT_FUNCTION4(libbinder_ndk, void, APersistableBundle_putStringVector, APersistableBundle*, const char*, const char* const*, int32_t)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, void, APersistableBundle_putPersistableBundle, APersistableBundle*, const char*, const APersistableBundle*)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, bool, APersistableBundle_getBoolean, const APersistableBundle*, const char*, bool*)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, bool, APersistableBundle_getInt, const APersistableBundle*, const char*, int32_t*)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, bool, APersistableBundle_getLong, const APersistableBundle*, const char*, int64_t*)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, bool, APersistableBundle_getDouble, const APersistableBundle*, const char*, double*)
HYBRIS_IMPLEMENT_FUNCTION5(libbinder_ndk, int32_t, APersistableBundle_getString, const APersistableBundle*, const char*, char**, APersistableBundle_stringAllocator, void*)
HYBRIS_IMPLEMENT_FUNCTION4(libbinder_ndk, int32_t, APersistableBundle_getBooleanVector, const APersistableBundle*, const char*, bool*, int32_t)
HYBRIS_IMPLEMENT_FUNCTION4(libbinder_ndk, int32_t, APersistableBundle_getIntVector, const APersistableBundle*, const char*, int32_t*, int32_t)
HYBRIS_IMPLEMENT_FUNCTION4(libbinder_ndk, int32_t, APersistableBundle_getLongVector, const APersistableBundle*, const char*, int64_t*, int32_t)
HYBRIS_IMPLEMENT_FUNCTION4(libbinder_ndk, int32_t, APersistableBundle_getDoubleVector, const APersistableBundle*, const char*, double*, int32_t)
HYBRIS_IMPLEMENT_FUNCTION6(libbinder_ndk, int32_t, APersistableBundle_getStringVector, const APersistableBundle*, const char*, char**, int32_t, APersistableBundle_stringAllocator, void*)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, bool, APersistableBundle_getPersistableBundle, const APersistableBundle*, const char*, APersistableBundle**)
HYBRIS_IMPLEMENT_FUNCTION5(libbinder_ndk, int32_t, APersistableBundle_getBooleanKeys, const APersistableBundle*, char**, int32_t, APersistableBundle_stringAllocator, void*)
HYBRIS_IMPLEMENT_FUNCTION5(libbinder_ndk, int32_t, APersistableBundle_getIntKeys, const APersistableBundle*, char**, int32_t, APersistableBundle_stringAllocator, void*)
HYBRIS_IMPLEMENT_FUNCTION5(libbinder_ndk, int32_t, APersistableBundle_getLongKeys, const APersistableBundle*, char**, int32_t, APersistableBundle_stringAllocator, void*)
HYBRIS_IMPLEMENT_FUNCTION5(libbinder_ndk, int32_t, APersistableBundle_getDoubleKeys, const APersistableBundle*, char**, int32_t, APersistableBundle_stringAllocator, void*)
HYBRIS_IMPLEMENT_FUNCTION5(libbinder_ndk, int32_t, APersistableBundle_getStringKeys, const APersistableBundle*, char**, int32_t, APersistableBundle_stringAllocator, void*)
HYBRIS_IMPLEMENT_FUNCTION5(libbinder_ndk, int32_t, APersistableBundle_getBooleanVectorKeys, const APersistableBundle*, char**, int32_t, APersistableBundle_stringAllocator, void*)
HYBRIS_IMPLEMENT_FUNCTION5(libbinder_ndk, int32_t, APersistableBundle_getIntVectorKeys, const APersistableBundle*, char**, int32_t, APersistableBundle_stringAllocator, void*)
HYBRIS_IMPLEMENT_FUNCTION5(libbinder_ndk, int32_t, APersistableBundle_getLongVectorKeys, const APersistableBundle*, char**, int32_t, APersistableBundle_stringAllocator, void*)
HYBRIS_IMPLEMENT_FUNCTION5(libbinder_ndk, int32_t, APersistableBundle_getDoubleVectorKeys, const APersistableBundle*, char**, int32_t, APersistableBundle_stringAllocator, void*)
HYBRIS_IMPLEMENT_FUNCTION5(libbinder_ndk, int32_t, APersistableBundle_getStringVectorKeys, const APersistableBundle*, char**, int32_t, APersistableBundle_stringAllocator, void*)
HYBRIS_IMPLEMENT_FUNCTION5(libbinder_ndk, int32_t, APersistableBundle_getPersistableBundleKeys, const APersistableBundle*, char**, int32_t, APersistableBundle_stringAllocator, void*)

#include <android/binder_ibinder.h>

HYBRIS_IMPLEMENT_FUNCTION4(libbinder_ndk, AIBinder_Class*, AIBinder_Class_define, const char*, AIBinder_Class_onCreate, AIBinder_Class_onDestroy, AIBinder_Class_onTransact)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, void, AIBinder_Class_setOnDump, AIBinder_Class*, AIBinder_onDump)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, void, AIBinder_Class_disableInterfaceTokenHeader, AIBinder_Class*)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, AIBinder*, AIBinder_new, const AIBinder_Class*, void*)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, bool, AIBinder_isRemote, const AIBinder*)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, bool, AIBinder_isAlive, const AIBinder*)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, binder_status_t, AIBinder_ping, AIBinder*)
HYBRIS_IMPLEMENT_FUNCTION4(libbinder_ndk, binder_status_t, AIBinder_dump, AIBinder*, int, const char**, uint32_t)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, binder_status_t, AIBinder_linkToDeath, AIBinder*, AIBinder_DeathRecipient*, void*)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, binder_status_t, AIBinder_unlinkToDeath, AIBinder*, AIBinder_DeathRecipient*, void*)
HYBRIS_IMPLEMENT_FUNCTION0(libbinder_ndk, uid_t, AIBinder_getCallingUid)
HYBRIS_IMPLEMENT_FUNCTION0(libbinder_ndk, pid_t, AIBinder_getCallingPid)
HYBRIS_IMPLEMENT_FUNCTION0(libbinder_ndk, bool, AIBinder_isHandlingTransaction)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, void, AIBinder_incStrong, AIBinder*)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, void, AIBinder_decStrong, AIBinder*)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, int32_t, AIBinder_debugGetRefCount, AIBinder*)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, bool, AIBinder_associateClass, AIBinder*, const AIBinder_Class*)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, const AIBinder_Class*, AIBinder_getClass, AIBinder*)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, void*, AIBinder_getUserData, AIBinder*)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, binder_status_t, AIBinder_prepareTransaction, AIBinder*, AParcel**)
HYBRIS_IMPLEMENT_FUNCTION5(libbinder_ndk, binder_status_t, AIBinder_transact, AIBinder*, transaction_code_t, AParcel**, AParcel**, binder_flags_t)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, AIBinder_Weak*, AIBinder_Weak_new, AIBinder*)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, void, AIBinder_Weak_delete, AIBinder_Weak*)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, AIBinder*, AIBinder_Weak_promote, AIBinder_Weak*)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, AIBinder_DeathRecipient*, AIBinder_DeathRecipient_new, AIBinder_DeathRecipient_onBinderDied)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, void, AIBinder_DeathRecipient_setOnUnlinked, AIBinder_DeathRecipient*, AIBinder_DeathRecipient_onBinderUnlinked)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, void, AIBinder_DeathRecipient_delete, AIBinder_DeathRecipient*)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, binder_status_t, AIBinder_getExtension, AIBinder*, AIBinder**)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, binder_status_t, AIBinder_setExtension, AIBinder*, AIBinder*)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, const char*, AIBinder_Class_getDescriptor, const AIBinder_Class*)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, bool, AIBinder_lt, const AIBinder*, const AIBinder*)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, AIBinder_Weak*, AIBinder_Weak_clone, const AIBinder_Weak*)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, bool, AIBinder_Weak_lt, const AIBinder_Weak*, const AIBinder_Weak*)

#include <android/binder_shell.h>

HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, void, AIBinder_Class_setHandleShellCommand, AIBinder_Class*, AIBinder_handleShellCommand)

#include <android/binder_process.h>

HYBRIS_IMPLEMENT_FUNCTION0(libbinder_ndk, void, ABinderProcess_startThreadPool)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, bool, ABinderProcess_setThreadPoolMaxThreadCount, uint32_t)
HYBRIS_IMPLEMENT_FUNCTION0(libbinder_ndk, bool, ABinderProcess_isThreadPoolStarted)
HYBRIS_IMPLEMENT_FUNCTION0(libbinder_ndk, void, ABinderProcess_joinThreadPool)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, binder_status_t, ABinderProcess_setupPolling, int*)
HYBRIS_IMPLEMENT_FUNCTION0(libbinder_ndk, binder_status_t, ABinderProcess_handlePolledCommands)

#include <android/binder_manager.h>

HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, binder_exception_t, AServiceManager_addService, AIBinder*, const char*)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, binder_exception_t, AServiceManager_addServiceWithFlags, AIBinder*, const char*, const AServiceManager_AddServiceFlag)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, AIBinder*, AServiceManager_checkService, const char*)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, AIBinder*, AServiceManager_getService, const char*)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, binder_status_t, AServiceManager_registerLazyService, AIBinder*, const char*)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, AIBinder*, AServiceManager_waitForService, const char*)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, AServiceManager_NotificationRegistration*, AServiceManager_registerForServiceNotifications, const char*, AServiceManager_onRegister, void*)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, void, AServiceManager_NotificationRegistration_delete, AServiceManager_NotificationRegistration*)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, bool, AServiceManager_isDeclared, const char*)
// Skip AServiceManager_forEachDeclaredInstance, contains function pointer
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, bool, AServiceManager_isUpdatableViaApex, const char*)
// Skip AServiceManager_getUpdatableApexName, contains function pointer
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, void*, AServiceManager_openDeclaredPassthroughHal, const char*, const char*, int)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, void, AServiceManager_forceLazyServicesPersist, bool)
// Skip AServiceManager_setActiveServicesCallback, contains function pointer
HYBRIS_IMPLEMENT_FUNCTION0(libbinder_ndk, bool, AServiceManager_tryUnregister)
HYBRIS_IMPLEMENT_FUNCTION0(libbinder_ndk, void, AServiceManager_reRegister)

#include <android/binder_parcel_platform.h>

HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, bool, AParcel_getAllowFds, const AParcel*)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, void, AParcel_markSensitive, const AParcel*)

#include <android/binder_stability.h>

HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, void, AIBinder_markSystemStability, AIBinder*)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, void, AIBinder_forceDowngradeToSystemStability, AIBinder*)
HYBRIS_IMPLEMENT_FUNCTION1(libbinder_ndk, void, AIBinder_markVintfStability, AIBinder*)

#include <android/binder_ibinder_platform.h>

HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, void, AIBinder_setRequestingSid, AIBinder*, bool)
HYBRIS_IMPLEMENT_FUNCTION0(libbinder_ndk, const char*, AIBinder_getCallingSid)
HYBRIS_IMPLEMENT_FUNCTION3(libbinder_ndk, void, AIBinder_setMinSchedulerPolicy, AIBinder*, int, int)
HYBRIS_IMPLEMENT_FUNCTION2(libbinder_ndk, void, AIBinder_setInheritRt, AIBinder*, bool)
