import os
import re
import sys
import subprocess

import cxxheaderparser.options
import cxxheaderparser.preprocessor
import cxxheaderparser.simple
import cxxheaderparser.types

# Preamable
print('''
/*
 * Auto-generated libhybris wrapper for libbinder_ndk.so.
 * See generator.py.
 *
 * The autogenerated file is considered to have the same copyright as the
 * input files.
 *
 * Copyright (C) 2018, The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <dlfcn.h>

extern "C" {
    #include <hybris/common/binding.h>
}

#ifndef __clang__
#   define _Nullable
#   define _Nonnull
#endif

HYBRIS_LIBRARY_INITIALIZE(libbinder_ndk, "libbinder_ndk.so")
''')

parser_options = cxxheaderparser.options.ParserOptions(
    preprocessor=cxxheaderparser.preprocessor.make_gcc_preprocessor(
        include_paths=['./include_ndk', './include_platform'],
        defines=['_Nullable ', '_Nonnull ']
    )
)

def params_contains_function_pointer(parameters: list[cxxheaderparser.types.Parameter]):
    for param in parameters:
        if isinstance(param.type, cxxheaderparser.types.Pointer) and \
                isinstance(param.type.ptr_to, cxxheaderparser.types.FunctionType):
            return True

    return False

def handle_one_file(file):
    print(f'\n#include <{"/".join(file.split("/")[2:])}>\n')

    parsed = cxxheaderparser.simple.parse_file(file, options=parser_options)
    for func in parsed.namespace.functions:
        if func.inline:
            continue

        if params_contains_function_pointer(func.parameters):
            # LibHybris macro can't represent it yet.
            print(f"// Skip {func.name.format()}, contains function pointer")
            continue

        print("HYBRIS_IMPLEMENT_FUNCTION{n_params}("
              "{libname}, {return_type}, {symbol}{params})"
              .format(
                n_params=len(func.parameters),
                libname='libbinder_ndk',
                return_type=func.return_type.format(),
                symbol=func.name.format(),
                params=''.join([f', {p.type.format()}' for p in func.parameters])
              ))

for hdr_file in os.scandir("./include_ndk/android/"):
    handle_one_file(hdr_file.path)

for hdr_file in os.scandir("./include_platform/android/"):
    handle_one_file(hdr_file.path)
